[user]
name = "John"
age = 30
[user.address]
street = "Main St"
city = "San Francisco"
[user.devices]
name = ["laptop", "phone", "tablet"]
[user.friends]
name = ["Tom", "Jack", "Amy"]
close = ["Tom", "Jack"]
[company]
name = "Example Inc"
[company.departments.1]
name = "Marketing"
team = ["John", "Tom"]
lead = "Tom"
[company.departments.2]
name = "Engineering"
team = ["Jack", "Amy"]
lead = "Jack"